name: 'Render Deployment'
author: 'Scheduling Workbox System <sws2apps.notification@gmail.com>'
description: 'A GitHub Action to trigger and track deployment in Render'
inputs:
  serviceId:
    description: 'The Service ID of your Render service'
    required: true
  apiKey:
    description: 'Your personal API key to interact with Render'
    required: false
  multipleDeployment:
    description: 'Specify if having multiple deployment is allowed'
    required: false
    default: true
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'play-circle'
  color: 'purple'
