name: 'Render Deployment'
author: 'Scheduling Workbox System <sws2apps.notification@gmail.com>'
description: 'A GitHub Action to trigger and track deployment in Render'
inputs:
  serviceId:
    description: 'The Service ID of your Render service'
    required: true
  apiKey:
    description: 'Your personal API key to interact with Render'
    required: true
  node-version:
    description: 'NodeJS Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0., lts/Jod'
    required: false
    default: 'lts/Jod'
  cli-version:
    description: 'Render CLI version from GitHub release'
    required: false
    default: '2.2.0'
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install Render CLI
      shell: bash
      run: |
        curl -fsSL https://raw.githubusercontent.com/render-oss/cli/refs/tags/v${{ inputs.cli-version }}/bin/install.sh | sh

    - name: Trigger deploy with Render CLI
      shell: bash
      env:
        RENDER_API_KEY: ${{ inputs.apiKey }}
        CI: true
      run: |
        render deploys create ${{ inputs.serviceId }} --output text --confirm --wait

branding:
  icon: 'play-circle'
  color: 'purple'
